### ISSUE TITLE
Learned on the PDP11...

### ISSUE THREAD

**Issue by PySimpleGUI** [timberwoof/PDP11#21]
Hi there!

I learned to code on a PDP11.

I saw you had an issue with PySimpleGUI and wondering if I might be able to help.  Happy to answer questions and see if there is a direction to take that may fit what you need.  The current docs are a bit of a mess.  The new ones will release with PySimpleGUI 5 soon.,  In the meantime, happy to help where I can...

What a great project you've got...

**Comment by timberwoof** [comment]
Thank you for your kind words. I've shown the project some love since then, and the GUI is in a more useful state. 
I tried to free the project from a GUI by talking directly to the console, but reading characters in a non-blocking way is apparently not possible without a great deal of work.

**Comment by timberwoof** [comment]
I poked around the PySimpleGUI docs but didn't see an obvious solution to my problem. 
PySimpleGUI multithreading has the concept of a long operation that runs and completes while the gui runs its events. In this application I have two (or three) loops: There's the CPU cycle loop that needs to run as fast as it can. And there are the two UI loops for the console and the VT52 emulator. The two UI loops need to occasionally send or receive bytes, but should not hold up the CPU loop. As I have it now, the UI windows take a lot of time. 
Is there an example somewhere of setting off a GUI loop into an independent thread from the main loop?

**Comment by timberwoof** [comment]
I gave it some more thought and inverted the threading model. The PDP11 emulator is now in a separate thread so the PySimpleGUI windows can be in Main the way they demand to be. The emulator is running at over 350,000 instructions per second. I need to implement some mutexes or semaphores.

**Comment by PySimpleGUI** [comment]
The threading model is dictated by tkinter, not PySimpleGUI.

Glad to see you got things running in threads.  There are a lot of examples using threads in the eCookbook, Cookbook, Demo Programs, and the PySimpleGUI applications.  

Wish I had more control over the threading, but tkinter actively checks..... the pypy version of Python has a tkinter version that won't allow the threading model that the cpython version is allowing us to use.....it used to be the fastest Python version I used, but have had to stop using it for now due to the threads problems.
