### ISSUE TITLE
MUL and negative values

### ISSUE THREAD

**Issue by outofmbufs** [timberwoof/PDP11#23]
The computation in MUL/pdp11_rss_ops.py is wrong. Says:

        a = self.reg.get(register)
        result = a * source  # results in a 32-bit number

Try -1 * -1 which should be 1, but this will give 0xFFFF * 0xFFFF = 0xFFFE0001 (high 16 = 0xFFFE; low 16 = 1)

Here's a SIMH session showing how it should behave:

    % pdp11

    PDP-11 simulator Open SIMH V4.1-0 Current        git commit id: 4e159a04
    sim> d r0 177777
    sim> d r1 177777
    sim> d -m 10000 mul r1,r0
    sim> d pc 10000
    sim> step

    Step expired, PC: 010002 (HALT)
    sim> e r0
    R0: 000000
    sim> e r1
    R1: 000001
    sim> e 10000
    10000: 070001

One algorithm that works is to sign-extend both operands to 32-bits and multiply those, something like:

    if a >= 32768:
        a |= 0xFFFF0000
    if source >= 32768:
        source |= 0xFFFF0000
    result = (source * a) & 0xFFFFFFFF

This assumes the Python/native values for 'a' and 'source' are 0 .. 65535 and never negative. I think there are other bugs that will allow values outside of 0 .. 65535 to appear here; those bugs need to be fixed separately.

**Comment by timberwoof** [comment]
I showed MUL and DIV some love, along with some data-driven testing including your test case. 
Thanks for pointing this out!

**Comment by outofmbufs** [comment]
Thanks. Also I think my other comment:

> I think there are other bugs that will allow values outside of 0 .. 65535 to appear here; those bugs need to be fixed separately.

is wrong; I misunderstood something else when thinking about this mul bug.
